### PR TITLE
Bump selected npm dependencies

### PR DESCRIPTION
**Pull request by anders-kiaer**

### CODE REVIEW

**Comment by rubenthoms** [comment]
I assume `package-lock.json` was automatically generated by npm?

**Comment by anders-kiaer** [comment]
> I assume `package-lock.json` was automatically generated by npm?

Yes 👍 Had to use `npm>=7` it looked like, in order to keep `lockfileVersion=2` (otherwise `npm` went back to `lockfileVersion=1` creating a unnecessarily large diff).

**Comment by rubenthoms** [comment]
> > I assume `package-lock.json` was automatically generated by npm?
> 
> Yes 👍 Had to use `npm>=7` it looked like, in order to keep `lockfileVersion=2` (otherwise `npm` went back to `lockfileVersion=1` creating a unnecessarily large diff).

In that case I'll just trust npm and assume the lock file is correct ;) Could not find any weird settings.

**Review by rubenthoms — APPROVED** [review]
LGTM!

**Pull request merged**
